[workspace]
members = ["crates/dale-syn", "crates/dale-util"]
resolver = "3"

[workspace.package]
version = "0.1.0"
authors = ["Daniel Drodt <daniel.drodt@tu-darmstadt.de>"]
edition = "2024"
license = "MIT"
repository = ""

[profile.release]
codegen-units = 1
lto = "fat"
